server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

sql:
  driver: mysql
  data_source_name: root:abcd1234@/masterdata2?charset=utf8&parseTime=True&loc=Local

retry2:
  1: 5
  2: 7
  3: 9

reader:
  kafka:
    brokers: tricycle-01.srvs.cloudkafka.com:9094
    client:
      username: ah1t9hk0
      password: QvMB75cxJ48KYRnGfwXcRNxzALyAeb7-
    group_id: my-group
    topic: ah1t9hk0-default
  retry:
    retry_count_name: retry
    limit_retry: 3
    goroutines: false

writer2:
  brokers:
    - tricycle-01.srvs.cloudkafka.com:9094
    - tricycle-02.srvs.cloudkafka.com:9094
    - tricycle-03.srvs.cloudkafka.com:9094
  client:
    username: ah1t9hk0
    password: QvMB75cxJ48KYRnGfwXcRNxzALyAeb7-
  topic: ah1t9hk0-default