server:
  name: go-subscription
  port: 8080

log:
  level: info

firestore:
  credentials: '
    {
      "type": "service_account",
      "project_id": "go-firestore-rest-api",
      "private_key_id": "6b1620dcbaa47bfc0ddda412cf8612519b41c875",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCckrKXCNNM8OQg\nQ3PUkX74ckRzVvD15I3GUow5hhb0aVW7rzA+ZvYFxRcpq9QZlJAWFc+filIorT7O\nDYW4xt0u+yzLCDa+tIejvL/ecQ7f2GEmiN4JUgMHHNP+zgMaC3rzbUuDUmjaEjjz\nrMqdjd8elg9ZY91rw5gkMOelG8ifYx/fd4H9gUwAejtIscqZ2KZRSY5lYsJlDRbI\nS7fCFMFZKlyTj576w3BI84YrwaifMF/Ogf87fz6Wf6DS16Aog7eKzhrlRGKd+yqL\n7wFoPK4nQdqEr0Cnr2mhUKTwSavQHB4kZlDwiZSwKY8AFo/WjNPekqUhNlPcJu3q\nCatbr2wHAgMBAAECggEAE42SYKAz2xZI4ZVANYScqaQuKNqWVEQ1nFXEuI5RTDaM\nrq1DG206PiA4iKCyZ9C7abam62ftDggMoX440TQsfRMrAIlHD5Z19fG6uFRqz3OI\ni7UTSBtbe3Doh0KXn+ddHwyVczyVvDNYX2iYaQfwRt6QjiZANEFZ553KipOnVe1r\nWHa99twnxt+XWHoJUHO1RyI6FrNOw+K+Coj1reQnS7/1QXaixe0/p0Wwo6qdUsEy\n2ftm8N7UsLCa5kWT3x8/XJfi50VvgleHSfGsW+Vj/tojljv0enXbwFtFqRs44evv\nwhDI4qOclUy3hNMbkc8d54S2zvWbRuv+BsklJU8gIQKBgQDTK2zyi+uXYR+DJYL6\nWqbrQoVkzmU7Sq2BQMq5/m/BncRPkAEdaQ1DyLpM6fwNp/FntYcu4FGI76bvJsji\nnAwRalAqOzu4d8YnUNbsaHFB+wELmA/a/oymyNL7pOnfjhq+QQlF0TJsV/ZZKFWG\nz7aKSGvKVxhvu6oAHK6r3GqkEQKBgQC90BM+GUeXes8E6l4lQlJNBatHLqlci/a8\n/r2NOd//CVaxSjWiYmf/zANNC6lG7X3KTI/PVhZQ5TVFzd2wpnJA9tymDDrP67QH\nSEjg7sQDQ9gM+yvhni1xCyxIU8gVVQdhOP/ih47RPAoQGmFRm48YJ+TTBYjOhGq3\nL2EcLSxGlwKBgQDD4JkrlxyOi7nGVepbvfDtcwP3UPhX+lpc9bPWuSwDBgwN3T8b\nf9GdGbmuFLEIHctwbtMZaVxYUCyh03Etup/7G4mG0vD/mKKG35atLeg40tLSZVf3\nxHzFTK1gXUXPZ6po5jzqtTU3iJRreV10MoJZXPoXc5ioNARqHDDuHAQTcQKBgFQB\nnBKWw52iJ69IPsSEtsIJ6UUGvMQN2fTJVYEEhUNtkaXDbztgDCEk3K0jpRaUE2EO\nQ3OC6TuCRfKP6za8Y8Kmvv7qWLke2z2B22dZpPzA8QTFwSUIiZoHVODp25q9WBfK\nT02lqyqlRNrdogapL0qElXxjbang5w4N9Q+wWnEfAoGAFnDhTzlb3nsYAvVe8OMP\nsm6x4u0OZRkJ+Z+m6CA19RgV0snOXwH8To9HzXFgnLA7l0EDgqEAgas2PE16nJtb\nEWABTOcXMdmlxLPinp8ejpb6eIaI+uIBF6A8my/sIB+XPZvKWV+FTnySv5KDJ3RL\nOI5ZGIDQDdE+QOqwu4Qjmzk=\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-srrcy@go-firestore-rest-api.iam.gserviceaccount.com",
      "client_id": "101673912751802204503",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-srrcy%40go-firestore-rest-api.iam.gserviceaccount.com"
    }'

retry:
  1: 5
  2: 7
  3: 9

sub:
  pubsub:
    client:
      credentials: '
        {
          "type": "service_account",
          "project_id": "go-firestore-rest-api",
          "private_key_id": "df1e6c245486c90c182edba78ecd0d4af7ecb994",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXwGvPmHrOC9m1\n+w8i/849avMpy4xrOxWWfXn1YB/Kr4n38G94Xrqa3xBPsOtm6oYlwrheTL7MxdWH\nk4MzHPkNnSzpYOOBSDS1gKRA0Rz14UA76TCwGKuijdtj4Fr0d1SuHgX5tlBTPAj7\n2YV5/feOtZds8ME61NO0C5ep2LKygG0KQpdSfL9cLtUsfFYv+xmPeTSn3yu84maY\nmIWiXHRXUsVjmzkFIy3aaTOze9hvFg3qAlXP2DvAJgVR4PS2b47ADFvMVzo0gn0I\nbdfXK1wAFQg4PgbIk2Rdwe5BWnI34K34ZVTxHfHZASfyDhHWg5+dKxkhrJR/ISIT\nsTmvSL3TAgMBAAECggEAN2kIZ1MaaxO5ENdPTmZTUgvHMrs/r4SHqVRFf8L1t0j5\nDq/1+PyfQUo7trPR6WcfF9CYKEPeltnSWtUEU5rDzf7Je5CyLVBdlSXaSXlLTkzR\nAfIEWp2jawayy0ZiJboGCgfU8gqkO5RGHGSDts6Gh2TU5Jo6jkD9tBZsF6d7UYNY\nRu8BkVNueNT/j9Nem6hzx1aux5gchIiEwjYnteDsZZBhNEPzilETXGAuT5UcVB2j\njgtX66+2mp1X76cdo1hk31vzrYxpsV1TqgsDAJzDToT1keWSWslWwx3xOUwHPs8N\nYfyuj+H71qZZiraTWiaN4kLJThJBtkbUJCjbPf8D/QKBgQD6ifBLH0dDnYXb2wsB\nrsX9SdwIz6XUqSg/n0T74lf/ABX4znadUzzfxGlB2EGqQ529Oxn+M2iChP667YVK\nMbuoqws/+CvXgrr6OF2qS74hajBpE/fIYIqdKZD7JbZAd6czyNEeRPwmu3xA+SH4\nTtGxg8WrRbu5M404w87KKwuOnQKBgQDcdFzI3i4GsglbzYYCLrW1WCPKGJey22fR\ngA3XZPp7+t2TVN9gjGQbvEFKNGzOiUCy4Y6ZQVJH8ALolExBHdj0Hdvl3X3XMB//\n93vWlP1NhGPwjZsthqINSk94Vxlxv2YPriEXblHQdZ4lsCZ3KhTeK4QNeHoUqk1q\njjx4XusbLwKBgEVuSKto5aT1WI1PLMOwnanN+C5w7TH8Fu1axBFR7rT6Xxxuiyya\nTrpsggb/WWNIDcTNRizOLl5NYRKIlHG1Sp45mIqHyg6Vah/B0yNIjk5QUU4tfHOJ\nXaCkTktrbhB7mFifhGRxFbfeKVcQM7vOjAo3zGXkk1uFz9M1YG9icnd5AoGAHEXc\nJHLCKl+o7ZolJqCA81nzdRbEVc7nuKmYnNg5e68Hvb5zy3kV2azCHtcsYSyfHJHq\n7OLAv7MbXGKwiOVgDqbJrehDHFbys6w0uKdw+QESpCY1EZijrdqq6H8bJ0hpuXcW\njV+7pGWBO8oklMHT3U5taCDcX0wcE59cR/+8XUcCgYEAz7ly/vY82s+beEVcpbbZ\nIw1tmOCkzPywQcePrSX+rPGdShYeiwQmprbZWiKyTYREUKkr2xt23A0irSgG3KOW\nWOZ0uswzj5r7VEnQflbAXhQLONRBWGHZZYdJ1GEqVlhb0A4j3xsw7jnB1Ypwfmbl\niiPXdFzuEX2Q3on3AfThMgw=\n-----END PRIVATE KEY-----\n",
          "client_email": "pubsub@go-firestore-rest-api.iam.gserviceaccount.com",
          "client_id": "112269970918400710901",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/pubsub%40go-firestore-rest-api.iam.gserviceaccount.com"
        }'
    subscription_id: users-sub
    subscription:
      max_outstanding_messages: 10000000
      num_goroutines: 5
  retry:
    retry_count_name: retry
    limit_retry: 3
    goroutines: false

pub:
  client:
    credentials: '
      {
       "type": "service_account",
       "project_id": "go-firestore-rest-api",
       "private_key_id": "df1e6c245486c90c182edba78ecd0d4af7ecb994",
       "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXwGvPmHrOC9m1\n+w8i/849avMpy4xrOxWWfXn1YB/Kr4n38G94Xrqa3xBPsOtm6oYlwrheTL7MxdWH\nk4MzHPkNnSzpYOOBSDS1gKRA0Rz14UA76TCwGKuijdtj4Fr0d1SuHgX5tlBTPAj7\n2YV5/feOtZds8ME61NO0C5ep2LKygG0KQpdSfL9cLtUsfFYv+xmPeTSn3yu84maY\nmIWiXHRXUsVjmzkFIy3aaTOze9hvFg3qAlXP2DvAJgVR4PS2b47ADFvMVzo0gn0I\nbdfXK1wAFQg4PgbIk2Rdwe5BWnI34K34ZVTxHfHZASfyDhHWg5+dKxkhrJR/ISIT\nsTmvSL3TAgMBAAECggEAN2kIZ1MaaxO5ENdPTmZTUgvHMrs/r4SHqVRFf8L1t0j5\nDq/1+PyfQUo7trPR6WcfF9CYKEPeltnSWtUEU5rDzf7Je5CyLVBdlSXaSXlLTkzR\nAfIEWp2jawayy0ZiJboGCgfU8gqkO5RGHGSDts6Gh2TU5Jo6jkD9tBZsF6d7UYNY\nRu8BkVNueNT/j9Nem6hzx1aux5gchIiEwjYnteDsZZBhNEPzilETXGAuT5UcVB2j\njgtX66+2mp1X76cdo1hk31vzrYxpsV1TqgsDAJzDToT1keWSWslWwx3xOUwHPs8N\nYfyuj+H71qZZiraTWiaN4kLJThJBtkbUJCjbPf8D/QKBgQD6ifBLH0dDnYXb2wsB\nrsX9SdwIz6XUqSg/n0T74lf/ABX4znadUzzfxGlB2EGqQ529Oxn+M2iChP667YVK\nMbuoqws/+CvXgrr6OF2qS74hajBpE/fIYIqdKZD7JbZAd6czyNEeRPwmu3xA+SH4\nTtGxg8WrRbu5M404w87KKwuOnQKBgQDcdFzI3i4GsglbzYYCLrW1WCPKGJey22fR\ngA3XZPp7+t2TVN9gjGQbvEFKNGzOiUCy4Y6ZQVJH8ALolExBHdj0Hdvl3X3XMB//\n93vWlP1NhGPwjZsthqINSk94Vxlxv2YPriEXblHQdZ4lsCZ3KhTeK4QNeHoUqk1q\njjx4XusbLwKBgEVuSKto5aT1WI1PLMOwnanN+C5w7TH8Fu1axBFR7rT6Xxxuiyya\nTrpsggb/WWNIDcTNRizOLl5NYRKIlHG1Sp45mIqHyg6Vah/B0yNIjk5QUU4tfHOJ\nXaCkTktrbhB7mFifhGRxFbfeKVcQM7vOjAo3zGXkk1uFz9M1YG9icnd5AoGAHEXc\nJHLCKl+o7ZolJqCA81nzdRbEVc7nuKmYnNg5e68Hvb5zy3kV2azCHtcsYSyfHJHq\n7OLAv7MbXGKwiOVgDqbJrehDHFbys6w0uKdw+QESpCY1EZijrdqq6H8bJ0hpuXcW\njV+7pGWBO8oklMHT3U5taCDcX0wcE59cR/+8XUcCgYEAz7ly/vY82s+beEVcpbbZ\nIw1tmOCkzPywQcePrSX+rPGdShYeiwQmprbZWiKyTYREUKkr2xt23A0irSgG3KOW\nWOZ0uswzj5r7VEnQflbAXhQLONRBWGHZZYdJ1GEqVlhb0A4j3xsw7jnB1Ypwfmbl\niiPXdFzuEX2Q3on3AfThMgw=\n-----END PRIVATE KEY-----\n",
       "client_email": "pubsub@go-firestore-rest-api.iam.gserviceaccount.com",
       "client_id": "112269970918400710901",
       "auth_uri": "https://accounts.google.com/o/oauth2/auth",
       "token_uri": "https://oauth2.googleapis.com/token",
       "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
       "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/pubsub%40go-firestore-rest-api.iam.gserviceaccount.com"
      }'
  topic_id: users
  topic:
    delay_threshold: 100
    count_threshold: 1