server:
  name: go-subscription
  port: 8080

log:
  level: info

mongo:
  uri: mongodb://localhost:27017
  database: masterdata

retry:
  1: 5
  2: 7
  3: 9

reader:
  sqs:
    region: us-west-2
    access_key_id: abc
    secret_access_key: abc
    queue_name: abc
  retry:
    retry_count_name: retry
    limit_retry: 3
    goroutines: false

writer:
  region: us-west-2
  access_key_id: abc
  secret_access_key: abc
  queue_name: abc