server:
  name: go-subscription
  port: 8080

log:
  level: info

sql:
  data_source_name: root:Mysqltuan2021@tcp(127.0.0.1:3306)/masterdata?parseTime=true

retry:
  1: 5
  2: 7
  3: 9

ibmmq:
  subscriber_config:
    queue_manager: "Test"
    queue_name: "test"
    channel_name: "CLOUD.ADMIN.SVRCONN"
    connection_name: "test-764e.qm.au-syd.mq.appdomain.cloud(31723)"
  queue_config:
    queue_manager: "Test"
    queue_name: "test"
    channel_name: "CLOUD.ADMIN.SVRCONN"
    connection_name: "test-764e.qm.au-syd.mq.appdomain.cloud(31723)"
  mq_auth:
    user_id: "pnhattuan"
    password: "-0McyERIrfgksLBu1kdHYEYpN0T4aSoOiCk2jzyfmzOm"