server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb://localhost:27017
  database: masterdata

retry:
  1: 5
  2: 7
  3: 9

consumer:
  rabbitmq:
    url: amqp://guest:guest@localhost:5672/
    exchange_name: test
    exchange_kind: fanout
    auto_delete: false
  retry:
    retry_count_name: retry
    limit_retry: 3
    goroutines: false

publisher:
  url: amqp://guest:guest@localhost:5672/
  exchange_name: test
  exchange_kind: fanout
  auto_delete: false
  content_type: text/plain
