server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: masterdata

retry:
  1: 5
  2: 7
  3: 9

subscriber:
  nats:
    subject: ah1t9hk0-default
    header: true
    connection:
      url: nats://localhost:4222
  retry:
    retry_count_name: retry
    limit_retry: 3
    goroutines: false

publisher:
  subject: ah1t9hk0-default
  header: true
  connection:
    url: nats://localhost:4222